### ISSUE TITLE
TV Shows , do not work as widgets , Movies seem to work fine 

### ISSUE THREAD

**Issue by SerpentDrago** [SerpentDrago/plugin.video.deepthought#9]
Movies (Tmdb/Trakt) appear to work fine from widgets , TVShows do not . 

Kodi 18 rc1 . 

```
10:36:31.969 T:31280   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.deepthought/tv/tvdb/
10:36:31.970 T:31148   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deepthought/tv/tvdb/) failed
10:36:35.148 T:31148   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:36:35.436 T:10132   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /tv/tvdb/
                                            Traceback (most recent call last):
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\default.py", line 1137, in <module>
                                                main()
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\default.py", line 1134, in main
                                                plugin.run()
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\resources\lib\xbmcswift2\plugin.py", line 333, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\resources\lib\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /tv/tvdb/
                                            -->End of Python script error report<--
10:36:35.476 T:31808   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.deepthought/tv/tvdb/
10:36:35.476 T:31148   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.deepthought/tv/tvdb/) failed
10:36:37.632 T:31148   ERROR: Control 50 in window 10025 has been asked to focus, but it can't
10:36:37.875 T:13480   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /tv/tvdb/
                                            Traceback (most recent call last):
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\default.py", line 1137, in <module>
                                                main()
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\default.py", line 1134, in main
                                                plugin.run()
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\resources\lib\xbmcswift2\plugin.py", line 333, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Serpe\Desktop\Kodi18 - Metalliq test\Kodi\portable_data\addons\plugin.video.deepthought\resources\lib\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /tv/tvdb/

```

**Comment by drinfernoo** [comment]
Here's what I've found so far.

The error states that there is `no matching view found for /tv/tvdb`, or basically, that path is invalid.

https://github.com/SerpentDrago/plugin.video.deepthought/blob/4f765bd69b829c2f13456a1444ade8b5e4f3dccb/resources/lib/meta/navigation/tvshows.py#L983

This line is where seasons *should* be being opened from... but it needs to be passed the TVDB id of the show in question, which the widget **isn't** doing. It **does** happen from within the add-on, as seen in this snippet from my `kodi.log` file.

`11:44:27.004 T:18016  NOTICE: [xbmcswift2] Request for "/tv/tvdb/279121" matches rule for function "tv_tvshow"`

Which matches on TVDB: 
![image](https://user-images.githubusercontent.com/2319508/49179003-2e7b8380-f306-11e8-808a-e0a9f2dd75cc.png)

But that information isn't getting passed through to the add-on from a widget.

**Comment by vitorp07** [comment]
How to reproduce, which widgets?
